### PR TITLE
Update azure-storage-common constraints

### PR DESCRIPTION
**Pull request by xylar**
A bit of tidying of the recipe.

Add @xylar as a maintainer.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Upstream lists this as the constraints:
https://github.com/Azure/azure-storage-python/blob/v2.1.0-file/azure-storage-file/setup.py#L75
and this is causing trouble with `pip check` downstream.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@xylar Probably we need to repodata patch the `0` build too as it will still be picked up by downstream builds.

**Review by xhochy — APPROVED** [review]

**Comment by xylar** [comment]
> Probably we need to repodata patch the 0 build too

That sounds good.  I don't know too much about how that works.

**Comment by xhochy** [comment]
https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/121/files is a good example probably. You need to adjust the `if` clause to match the `0` builds but otherwise this picks a version for a specific package and replaces one of the dependencies. Personally I like to run the `gen_patch_json.py` and set a breakpoint once the `if` clause matched to view the contents of `record` to see how I need to modify it.

**Comment by xylar** [comment]
Thanks @xhochy.  That doesn't look too hard.  I can put in a PR later today.

**Pull request merged**
